'use strict';
const {Game,KEYS,SPELLS,CX,CY,display,formatInput}=ForestCore;
const game=new Game();const $=id=>document.getElementById(id);const canvas=$('canvas'),ctx=canvas.getContext('2d');const bg=new Image();bg.src='forest-battlefield.png';
let fx=[],last=performance.now(),wall=0,shake=0,flash=0,sound=false,audio=null,best=null,previousMode='',toastTimer;
try{best=JSON.parse(localStorage.getItem('forest-watch-best-v1'))}catch{}
const fmt=t=>{const s=Math.floor(t);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
$('best').textContent=best?.time?fmt(best.time):'—';
function beep(freq,duration=.12,type='sine',volume=.045){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.55,audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2400)}
function start(){game.reset();fx=[];flash=0;shake=0;$('feedback').textContent='輸入魔物名字，即可施放目前法術。';$('feedback').className='';previousMode='';renderUI();beep(440)}
$('start').onclick=start;$('again').onclick=start;$('restartPaused').onclick=start;
$('home').onclick=()=>{game.mode='start';game.enemies=[];game.input='';renderUI()};$('pause').onclick=()=>{game.pause();renderUI()};$('resume').onclick=()=>{game.pause();renderUI()};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('game').requestFullscreen()}catch{toast('此瀏覽器無法開啟全螢幕，可改用瀏覽器的全螢幕功能。')}};
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=`音效 ${sound?'開':'關'}`;$('sound').setAttribute('aria-label',sound?'關閉音效':'開啟音效');beep(580)};
document.querySelectorAll('[data-spell]').forEach(b=>b.onclick=()=>{if(game.mode==='playing'){game.spell=+b.dataset.spell;renderUI()}});
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.isComposing||e.keyCode===229){if(['playing','ritual'].includes(game.mode))toast('請先切換成英文輸入法，再按注音對應鍵位。');return}if(e.key==='Escape'){e.preventDefault();game.pause();renderUI();return}if(!['playing','ritual'].includes(game.mode))return;const key=e.key.toLowerCase();if(KEYS[key]||['Backspace','Enter','Tab','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.repeat&&e.key!=='Backspace')return;
 if(e.key==='Tab')game.select(e.shiftKey?-1:1);else if(e.key==='ArrowLeft')game.changeSpell(-1);else if(e.key==='ArrowRight')game.changeSpell(1);else if(e.key==='Enter')game.submit();else game.type(e.key==='Backspace'?'Backspace':key);processEvents();renderUI();});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&['playing','ritual'].includes(game.mode)){game.pause();renderUI()}});
function processEvents(){for(const e of game.events){switch(e.type){case'arrow':fx.push({...e,life:.25,max:.25});break;case'cast':fx.push({...e,life:.6,max:.6});beep([340,220,520,680][e.spell]);$('feedback').textContent=`已施放${SPELLS[e.spell].name}，重新鎖定最近的魔物。`;$('feedback').className='good';break;case'wrong':beep(110,.2,'triangle');if(game.mode==='ritual'){$('ritualMessage').textContent='咒語不正確，已清空。看清楚聲調，再試一次。';$('ritualMessage').classList.add('bad')}else{$('feedback').textContent='名字不正確，已清空。請看清楚注音與聲調。';$('feedback').className='bad'}break;case'death':fx.push({...e,life:.9,max:.9});beep(740,.08,'sine',.02);break;case'clash':fx.push({...e,life:.2,max:.2});break;case'hurt':shake=.22;beep(80,.15,'triangle');break;case'ultimate':flash=1.2;for(let i=0;i<80;i++)fx.push({type:'spark',x:CX,y:CY,angle:Math.random()*Math.PI*2,speed:80+Math.random()*650,life:1.6,max:1.6});beep(1000,1,'sine',.12);toast(`曙光降臨！清除 ${e.count} 隻魔物`);break;case'ritual':beep(700,.8);break;case'end':saveResult();break;}}game.events=[];}
function saveResult(){const record=!best||game.time>best.time;let saved=true;if(record){best={time:game.time,kills:game.kills,casts:game.casts,accuracy:game.attempts?Math.round(game.correct/game.attempts*100):0};try{localStorage.setItem('forest-watch-best-v1',JSON.stringify(best))}catch{saved=false}$('best').textContent=fmt(best.time)}$('endTitle').textContent=record?'新的守望紀錄。':'火光仍會再燃。';$('endTime').textContent=fmt(game.time);$('endKills').textContent=game.kills;$('endCasts').textContent=game.casts;$('endAccuracy').textContent=game.attempts?`${Math.round(game.correct/game.attempts*100)}%`:'—';$('recordMessage').textContent=!saved?'瀏覽器無法儲存紀錄，本次成績仍顯示於此。':record?'你的最佳成績已儲存在此瀏覽器。':`個人最佳 ${fmt(best.time)}，再試一次吧。`}
function renderUI(){const mode=game.mode;const t=game.target();$('time').textContent=fmt(game.time);$('hp').textContent=`${Math.ceil(game.hp)} / 100`;$('hpbar').style.width=`${game.hp}%`;$('hpbar').style.background=game.hp<30?'#e9957d':'#a9c894';$('energy').textContent=`${game.energy} / ${game.energyMax}`;$('energybar').style.width=`${game.energy/game.energyMax*100}%`;$('kills').textContent=game.kills;$('target').textContent=t?display(t.entry):'—';$('targetType').textContent=t?`${t.orc?'獸人':'哥布林'} · Tab 切換`:'等待魔物現身';$('input').replaceChildren();if(game.input&&mode==='playing'){$('input').textContent=formatInput(game.input,t?.entry);$('input').classList.toggle('bad',!!t&&!t.entry.answer.startsWith(game.input))}else{const p=document.createElement('span');p.className='placeholder';p.textContent='在此輸入注音';$('input').append(p);$('input').classList.remove('bad')}
 $('phase').textContent=game.time<60?'森林邊境 · 單字試煉':game.time<180?'暗影漸深 · 雙字詞現身':'長夜守望 · 魔物持續增援';$('pause').disabled=['start','ended'].includes(mode);$('pause').textContent=mode==='paused'?'繼續':'暫停';document.querySelectorAll('[data-spell]').forEach(b=>{b.classList.toggle('active',+b.dataset.spell===game.spell);b.setAttribute('aria-pressed',String(+b.dataset.spell===game.spell))});
 if(mode!==previousMode){$('overlay').hidden=mode==='playing';for(const [id,m]of Object.entries({startPanel:'start',pausePanel:'paused',ritualPanel:'ritual',endPanel:'ended'}))$(id).hidden=mode!==m;if(mode==='ritual'){$('chant').textContent=display(game.chant);$('ritualMessage').textContent='完成後按 Enter，錯誤時會清空重打。';$('ritualMessage').classList.remove('bad')}previousMode=mode}if(mode==='ritual')$('ritualInput').textContent=formatInput(game.input,game.chant);
}
// Pixel sprites stay on the game canvas, independent of readable UI text.
const goblin=['....hh....','..hhhhhh..','h.hggggh.h','hhhgyyghhh','..gggggg..','...gggg...','..baaaab..','.bbaaaabb.','.bbaaaabb.','...bbbb...','...b..b...','..bb..bb..'];
const orc=['...hhhh...','..hhhhhh..','.hhgggghh.','hhgggggghh','.ggyrgyg..','.gggwggg..','..ggwwgg..','.bbbbbbbb.','bbaaaaaabb','bbaaaaaabb','..aaaaaa..','..bbbbbb..','..bb..bb..','.bbb..bbb.'];
function drawMonster(e){const stone=e.effects[1]>0,pal=stone?{h:'#82949e',g:'#a3b3ba',y:'#eef0d4',r:'#687983',w:'#e5ddd0',b:'#62717c',a:'#919aab'}:{h:e.orc?'#506547':'#3c6742',g:e.orc?'#83915a':'#8cad67',y:'#eac771',r:'#302222',w:'#dcd3ad',b:'#503c30',a:e.orc?'#835b48':'#7a7052'};const sprite=e.orc?orc:goblin;const s=e.orc?3:2.65;let y=e.y;const bob=stone?0:Math.sin(wall*7+e.id)*1.5;ctx.fillStyle='#06141777';ctx.beginPath();ctx.ellipse(e.x,y+6,e.orc?21:17,7,0,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(Math.round(e.x-sprite[0].length*s/2),Math.round(y-sprite.length*s+bob));for(let r=0;r<sprite.length;r++)for(let c=0;c<sprite[r].length;c++){const color=pal[sprite[r][c]];if(color){ctx.fillStyle=color;ctx.fillRect(c*s,r*s,s+.2,s+.2)}}ctx.restore();
 if(e.effects[2]>0){for(let i=0;i<4;i++){ctx.fillStyle=i%2?'#ffe18b':'#ed8852';ctx.fillRect(e.x-15+i*8,y-10-(Math.sin(wall*12+i)*6),4,9)}}if(e.effects[0]>0){ctx.fillStyle='#b1dc67';for(let i=0;i<3;i++)ctx.fillRect(e.x-15+i*13,y-32-((wall*15+i*9)%25),3,3)}if(e.effects[3]>0){ctx.strokeStyle='#cb9bed';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(e.x,y-48,15,4,wall,0,Math.PI*1.5);ctx.stroke()}if(stone){ctx.strokeStyle='#d7e5ebaa';ctx.lineWidth=2;ctx.strokeRect(e.x-19,y-43,38,46)}
 if(e.id===game.targetId){ctx.strokeStyle=SPELLS[game.spell].color;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(e.x,e.y+4,25,10,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle=SPELLS[game.spell].color;ctx.beginPath();ctx.moveTo(e.x-5,e.y-69);ctx.lineTo(e.x+5,e.y-69);ctx.lineTo(e.x,e.y-63);ctx.fill()}
}
function drawLabels(){const labels=[];ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='600 21px "PingFang TC", "Microsoft JhengHei", sans-serif';for(const e of [...game.enemies].sort((a,b)=>a.y-b.y)){const txt=display(e.entry),w=ctx.measureText(txt).width+20;let x=Math.max(w/2+12,Math.min(1200-w/2-12,e.x)),y=e.y-(e.orc?62:57);for(let tries=0;tries<6;tries++){if(labels.some(l=>Math.abs(l.x-x)<(l.w+w)/2+3&&Math.abs(l.y-y)<32))y-=33;else break}labels.push({x,y,w});if(Math.abs(y-(e.y-57))>20){ctx.strokeStyle='#c5cfaa55';ctx.beginPath();ctx.moveTo(x,y+17);ctx.lineTo(e.x,e.y-40);ctx.stroke()}ctx.fillStyle=e.id===game.targetId?'#17251ff0':'#091b20e8';ctx.fillRect(x-w/2,y-15,w,30);ctx.strokeStyle=e.id===game.targetId?SPELLS[game.spell].color:'#7d968157';ctx.lineWidth=1;ctx.strokeRect(x-w/2,y-15,w,30);ctx.fillStyle=e.id===game.targetId?'#f0ecc8':'#e0e8d9';ctx.fillText(txt,x,y);ctx.fillStyle='#243c31';ctx.fillRect(x-w/2,y+16,w,3);ctx.fillStyle=e.orc?'#d2a276':'#9bbd80';ctx.fillRect(x-w/2,y+16,w*Math.max(0,e.hp/e.maxHp),3)}}
function draw(dt){wall+=dt;ctx.clearRect(0,0,1200,760);ctx.save();if(shake>0){shake-=dt;ctx.translate(Math.sin(wall*95)*3,Math.cos(wall*87)*2)}if(bg.complete&&bg.naturalWidth)ctx.drawImage(bg,0,0,1200,760);else{ctx.fillStyle='#1b322a';ctx.fillRect(0,0,1200,760)}
 for(let i=0;i<18;i++){const x=(i*173+Math.sin(wall*.25+i)*35)%1200,y=(i*127+wall*3)%760;ctx.fillStyle=`rgba(207,223,148,${.15+.2*Math.sin(wall+i)})`;ctx.fillRect(x,y,2,2)}
 for(const e of [...game.enemies].sort((a,b)=>a.y-b.y))drawMonster(e);drawLabels();
 const active=game.mode==='playing';for(const f of fx){if(active)f.life-=dt;const p=1-f.life/f.max;ctx.globalAlpha=Math.max(0,f.life/f.max);if(f.type==='arrow'){ctx.strokeStyle='#f4d69c';ctx.lineWidth=2;const x=CX+(f.x-CX)*p,y=CY-80+(f.y-(CY-80))*p;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-(f.x-CX)*.1,y-(f.y-CY+80)*.1);ctx.stroke()}else if(f.type==='cast'){ctx.strokeStyle=SPELLS[f.spell].color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(f.x,f.y-20,10+p*32,0,Math.PI*2);ctx.stroke()}else if(f.type==='death'){const x=f.x+(CX-f.x)*p*p,y=f.y+(CY-60-f.y)*p*p;ctx.fillStyle='#c9b5f1';ctx.save();ctx.translate(x,y);ctx.rotate(Math.PI/4);ctx.fillRect(-4,-4,8,8);ctx.restore()}else if(f.type==='spark'){ctx.fillStyle='#ffe5a0';ctx.fillRect(f.x+Math.cos(f.angle)*f.speed*p,f.y+Math.sin(f.angle)*f.speed*p,4,4)}else{ctx.fillStyle='#edc398';ctx.fillRect(f.x-4,f.y-25,8,8)}}ctx.globalAlpha=1;fx=fx.filter(f=>f.life>0);if(flash>0){flash-=dt;ctx.fillStyle=`rgba(255,237,179,${Math.max(0,flash*.65)})`;ctx.fillRect(0,0,1200,760);ctx.strokeStyle=`rgba(255,237,179,${Math.max(0,flash)})`;ctx.lineWidth=16;ctx.beginPath();ctx.arc(CX,CY,(1.2-flash)*850,0,Math.PI*2);ctx.stroke()}ctx.restore();}
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;game.update(dt);processEvents();draw(dt);renderUI();requestAnimationFrame(frame)}renderUI();requestAnimationFrame(frame);
