const assert=require('node:assert/strict');
const {Game,WORDS}=require('../dist/core.js');
const g=new Game(()=>.2);g.reset();g.arrowIn=g.spawnIn=999;
const near=g.spawn(),far=g.spawn();near.entry=WORDS.find(w=>w.word==='山');far.entry=WORDS.find(w=>w.word==='水');near.x=660;near.y=387;far.x=1000;far.y=387;
g.input=far.entry.answer;g.submit();assert.equal(near.effects[0],0);assert.ok(far.effects[0]>0);assert.equal(g.input,'');
g.input='g';assert.equal(g.matches(true).length,2);g.type('0');assert.equal(g.matches(true)[0].id,near.id);g.submit();assert.equal(near.effects[0],0);assert.equal(g.input,'');
const twin=g.spawn();twin.entry=near.entry;twin.x=900;twin.y=387;g.input=near.entry.answer;g.submit();assert.ok(near.effects[0]>0);assert.equal(twin.effects[0],0);
g.input='g0';near.hp=0;g.update(.02);assert.equal(g.input,'g0');assert.equal(g.matches(true)[0].id,twin.id);g.type(' ');g.submit();assert.ok(twin.effects[0]>0);
g.input=far.entry.answer;far.hp=0;const casts=g.casts;g.submit();assert.equal(g.casts,casts);assert.equal(g.input,'');assert.equal(g.events.at(-1).type,'wrong');
g.enemies=[];g.type('s');g.update(.02);assert.equal(g.input,'s');g.submit();assert.equal(g.input,'');
console.log('PASS: 真名指定遠處魔物、前綴提示、聲調必填、同名最近優先、死亡保留輸入、排除死亡魔物及無相符提示。');
